name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-22.04
    steps:
      - name: Print Context
        run: echo "${{ toJSON(github) }}"