name: Deploy App
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test App
        run: npm run test
  lint:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint App
        run: npm run lint
  build:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Deploy
        run: echo deploy