name: Deploy App
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test App
        run: npm run test
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint App
        run: npm run lint
  build:
    runs-on: ubuntu-22.04
    needs: [lint, test]
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install Nose JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "dist/"
          args: |
            --delete
            --exclude '.git*'
            --exclude 'node_modules'
            --exclude 'logs'
            --exclude '.env'
            ./dist/* user@server:/path/to/app/
